# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HailstormDamageAssessment
                                 A QGIS plugin
 Satellite-based hailstorm damage assessment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-17
        copyright            : (C) 2022 by Aiswarya V V
        email                : aiswarya.ga20@iiitmk.ac.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HailstormDamageAssessment class from file HailstormDamageAssessment.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hail_impact import HailstormDamageAssessment
    return HailstormDamageAssessment(iface)
